sonar.projectKey=oficina-mvp
sonar.projectName=oficina-mvp
sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.ts
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
