apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - migrate-job.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml

# Tag sobrescrita em CI por: kustomize edit set image oficina-api=oficina-api:<sha>
images:
  - name: oficina-api
    newTag: latest
