---
# ClusterIP — comunicação interna entre Pods
apiVersion: v1
kind: Service
metadata:
  name: oficina-api
  namespace: oficina
spec:
  selector:
    app: oficina-api
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP

---
# NodePort — acesso externo via host (Kind mapeia 30080 → host:3000 via extraPortMappings)
apiVersion: v1
kind: Service
metadata:
  name: oficina-api-nodeport
  namespace: oficina
spec:
  selector:
    app: oficina-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort
