apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-api-config
  namespace: oficina
data:
  PORT: "3000"
  NODE_ENV: "production"
  SEED_DATA: "false"
  DB_HOST: "postgres.oficina.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "oficina_db"
