apiVersion: v1
kind: Secret
metadata:
  name: oficina-api-secrets
  namespace: oficina
type: Opaque
stringData:
  DATABASE_URL: "${database_url}"
  JWT_SECRET: "${jwt_secret}"
  EXTERNAL_WEBHOOK_TOKEN: "${external_webhook_token}"
